name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Build storybook
        run: npm run build:storybook

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-storybook
          path: ./storybook-static

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
      pages: write
      id-token: write


    steps:
      - name: Checkout repo (to access .git)
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-storybook
          path: ./build-storybook
      
      - name: Create docs folder
        run: mkdir ./dist/docs/

      - name: Copy Storybook files to docs folder
        run: mv ./build-storybook/* ./dist/docs/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist